### ISSUE TITLE
Failing tests for version 0.2.0

### ISSUE THREAD

**Issue by apaatsio** [leisim/auto_size_text#2]
The tests are failing for the 0.2.0 release: https://travis-ci.com/leisim/auto_size_text/builds/85639827

Is the version 0.2.0 supposed to work? I can't get it to work. Even when I'm trying something like `AutoSizeText('foo', minFontSize: 50.0, maxFontSize: 100.0)` the text is rendered at the default font size (12.0).

**Comment by leisim** [comment]
I didn't have time yet to write the tests. There are a few old ones which fail.

I'm already using v0.2.0 in production and it works perfectly.
Could you show me how you use the widget?

You can also try the [demo](https://github.com/leisim/auto_size_text/tree/master/demo) app.

**Comment by apaatsio** [comment]
Here's a simple example app that is not working expectedly for me:

```dart
Widget build(BuildContext context) {
  return MaterialApp(
    home: SafeArea(
      top: true,
      child: Material(
        child: Row(
          children: [
            Expanded(
              child: AutoSizeText(
                'This should be at least size 25.0',
                minFontSize: 25.0,
              ))]))));
}
```

**Comment by leisim** [comment]
Thank you! I can reproduce the problem and I'm working on it ;)

**Comment by leisim** [comment]
Sorry for the inconvenience. It should work now. Please open the issue again if there are still problems.

**Comment by apaatsio** [comment]
Now the minFontSize works in the sense that the font size is exactly at minFontSize. But it still doesn't stretch the text to the full width of the screen (using the code example I posted in the earlier comment).

![2018-10-10 15 25 31](https://user-images.githubusercontent.com/195210/46739457-e0041e00-cca0-11e8-93fe-6b38c13935c0.png)

**Comment by leisim** [comment]
The font size does not exceed the `fontSize` of your `TextStyle` (or the inherited `fontSize` if none is set). Try something like
```dart
AutoSizeText(
  "This should work now",
  style: TextStyle(fontSize:100.0),
  minFontSize: 25.0,
)
```

**Comment by apaatsio** [comment]
Ok, that way it works exactly as I want. Thanks!
